export { Home } from "../partial/Home";
export { About } from "../partial/About";
export { Donation } from "../partial/Donation";
export { News } from "../partial/News";
export { Provinces } from "../partial/Provinces";
export { Municipality } from "../partial/Municipality";
export { Barangay } from "../partial/Barangay";
export { BarangayAbout } from "../partial/BarangayAbout";
export { SignIn } from "../partial/SignIn";
export { Upload } from "../partial/Upload";
export { Image } from "../partial/Image";
export { UploadVideo } from "../partial/UploadVideo";
export { UploadImage } from "../partial/UploadImage";
export { MunicipalityAbout } from "../partial/MunicipalityAbout";
export { Faq } from "../partial/Faq";
export { PageNotFound } from "../partial/PageNotFound";
export { Testing } from "../partial/Testing";
export { DashBoard } from "../partial/DashBoard";
export { TestingPurposes } from "../partial/TestingPurposes"
